Repository aeternity/aeternity, pull requests merged in 2019-11, with the labels that each got.

#2968 Improve close solo and force progress checks and tests
  apps/aechannel/src/aesc_utils.erl
  apps/aechannel/test/aesc_txs_SUITE.erl
  docs/release-notes/next-lima/GH-2964_sc_tighten_up_checks.md
Labels: area/statechannels

#2969 Prepare v5.0.2
  VERSION
  apps/aehttp/priv/swagger.yaml
  ci/appveyor/package.cfg
  docs/installation.md
  docs/release-notes/RELEASE-NOTES-5.0.2.md
  docs/release-notes/next-lima/GH-2964_sc_tighten_up_checks.md
  docs/release-notes/next/cache_contract_creator.md
Labels: release

#2954 Propagate noise session error to the client
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_listeners.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/src/aesc_session_noise_sup.erl
  apps/aechannel/src/aesc_sup.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
Labels: area/statechannels, kind/improvement

#2985 SC abort update: adapt messages for client
  apps/aechannel/src/aesc_fsm.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
Labels: area/statechannels, kind/cleanup

#2980 Improve test framework for FATE
  apps/aecontract/test/aect_test_utils.erl
  apps/aefate/test/aefa_sophia_test.erl
Labels: area/core, kind/improvement

#2981 Update mnesia_leveled dep
  rebar.config
  rebar.lock
Labels: area/db, kind/bug

#2995 SC: improve slash and tests
  apps/aechannel/src/aesc_channels.erl
  apps/aechannel/src/aesc_utils.erl
  apps/aechannel/test/aesc_txs_SUITE.erl
  docs/release-notes/next/sc_solo_round_hotfix.md
Labels: area/statechannels, kind/bug

#2992 Add meta info support for all offchain updates
  apps/aechannel/src/aesc_fsm.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next/GH-2987-meta-for-all-updates.md
Labels: area/statechannels, kind/feature

#2996 SC: improve force progress stability
  apps/aechannel/src/aesc_channels.erl
  apps/aechannel/src/aesc_force_progress_tx.erl
  apps/aechannel/src/aesc_utils.erl
  apps/aechannel/test/aesc_txs_SUITE.erl
  docs/release-notes/next/sc_fp_solo_round.md
Labels: area/statechannels, kind/bug

#2993 Improve slash tests
  apps/aechannel/test/aesc_txs_SUITE.erl
Labels: area/statechannels, kind/cleanup

#2982 Add protocol activated by miner singnalling to HTTP /status
  apps/aehttp/priv/swagger.yaml
  apps/aehttp/src/aehttp_dispatch_ext.erl
  docs/release-notes/next-lima/GH-2957-add-protocol-activated-by-miner-signalling-to-status.md
  system_test/common/aest_community_fork_SUITE.erl
Labels: area/api, kind/improvement

#3000 Fix CI naming of windows builds for versioned releases
  .circleci/config.yml
  .circleci/windows/build.sh
Labels: area/ci

#3001 Sync master with 5.1.0-rc.1
  VERSION
  apps/aehttp/priv/swagger.yaml
  docs/installation-windows.md
  docs/installation.md
  docs/release-notes/RELEASE-NOTES-5.1.0-rc.1.md
  docs/release-notes/next-lima/GH-2957-add-protocol-activated-by-miner-signalling-to-status.md
  docs/release-notes/next-lima/PT-160544356-sc-confirmation-times.md
  docs/release-notes/next-lima/PT-168782034-sc_load-regulation.md
  docs/release-notes/next-lima/miner-signalled-consensus.md
  docs/release-notes/next/GH-2951-sync-crash-loop-fix
  docs/release-notes/next/GH-2973-dont_duplicate_sync_tasks.md
  docs/release-notes/next/GH-2978-less_noise_while_syncing.md
  docs/release-notes/next/GH-2987-meta-for-all-updates.md
  docs/release-notes/next/PT-168289008_SC_soft_reject.md
  docs/release-notes/next/SC_FSM_optional_fees.md
  docs/release-notes/next/fate-maps-gc-hotfix.md
  docs/release-notes/next/sc_fp_solo_round.md
  docs/release-notes/next/sc_solo_round_hotfix.md
Labels: release

#3005 Prepare v5.1.0
  .circleci/config.yml
  .circleci/windows/build.sh
  VERSION
  apps/aehttp/priv/swagger.yaml
  docs/release-notes/RELEASE-NOTES-5.1.0.md
Labels: release

#2911 Replace state password with fsm id
  apps/aechannel/src/aesc_client.erl
  apps/aechannel/src/aesc_client_reconnect_tx.erl
  apps/aechannel/src/aesc_db.erl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_fsm_id.erl
  apps/aechannel/src/aesc_offchain_state.erl
  apps/aechannel/src/aesc_state_cache.erl
  apps/aechannel/src/aesc_state_password_wrapper.erl
  apps/aechannel/src/aesc_utils.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/src/aec_db.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/src/sc_ws_utils.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aehttp/test/aehttp_ws_test_utils.erl
  apps/aetx/src/aetx.erl
  docs/release-notes/next/GH-2822-session-token-encryption.md
  system_test/common/helpers/aest_api.erl
Labels: area/statechannels

#3008 add vm_version to fate's engine state record
  apps/aecontract/src/aect_dispatch.erl
  apps/aefate/src/aefa_engine_state.erl
  apps/aefate/src/aefa_fate.erl
  apps/aefate/test/aefa_sophia_test.erl
  apps/aefate/test/aefate_engine_test.erl
Labels: area/fate, kind/improvement

#3012 Add aec_db write throughput test
  apps/aecore/test/aec_db_tests.erl
Labels: area/db, area/tests, kind/improvement

#3018 Trigger CI on PRs from forks
  .circleci/config.yml
Labels: area/ci, kind/improvement

#3020 Update dependency sha3
  rebar.config
  rebar.lock
Labels: kind/improvement

#2984 Add database write retry
  apps/aechannel/src/aesc_fsm.erl
  apps/aecore/src/aec_chain_state.erl
  apps/aecore/src/aec_conductor.erl
  apps/aecore/src/aec_db.erl
  apps/aecore/src/aec_db_error_store.erl
  apps/aecore/src/aecore_sup.erl
  apps/aecore/test/aec_chain_state_tests.erl
  apps/aecore/test/aec_conductor_tests.erl
  apps/aecore/test/aec_db_tests.erl
  apps/aecore/test/aec_test_utils.erl
  apps/aecore/test/aec_tx_pool_tests.erl
  apps/aecore/test/aecore_app_tests.erl
  apps/aeutils/priv/aeternity_config_schema.json
  docs/release-notes/next/GH-2974_db_write_retry.md
  rebar.config
  rebar.lock
Labels: area/db, kind/improvement

#3025 aeo_oracles:serialize_for_client should encode FATE_ABI data
  apps/aeoracle/src/aeo_oracles.erl
  docs/release-notes/next/GH-3021-encode_fate_abi_data_for_oracle.md
Labels: area/oracle

#3024 Set revision to unknown when not available
  Makefile
Labels: area/build-system, kind/bug

#3003 Remove Pivotal Tracker
  README.md
Labels: area/docs, kind/cleanup

#3029 Log peer connection count periodically
  apps/aecore/src/aec_peers.erl
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/test/data/epoch_full.yaml
  docs/release-notes/next/GH-2168-peer-conn-count-log.md
Labels: area/core, kind/feature

#3036 Update OTP versions to match builder
  .circleci/config.yml
Labels: area/build-system

#3019 Add nix expression to get working development environment
  .circleci/config.yml
  default.nix
Labels: area/build-system, kind/improvement

#3034 Add number of peer connections to HTTP /status
  apps/aehttp/priv/swagger.yaml
  apps/aehttp/src/aehttp_dispatch_ext.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  docs/release-notes/next/GH-3033-fix-number-of-peers-in-http-status.md
Labels: area/api, kind/feature

#2991 Allow reading genesis accounts from prepopulated file
  system_test/common/helpers/aest_docker.erl
Labels: area/tests, kind/improvement

#3043 GH-2850 Add FATE support for BLS12-381 crypto operations
  .circleci/config.yml
  Dockerfile
  Makefile
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/test/aec_eunit_SUITE.erl
  apps/aefate/src/aefa_fate_op.erl
  apps/aefate/src/aefate.app.src
  default.nix
  docs/build.md
  rebar.config
  rebar.lock
  test/contracts/crypto_pairing.aes
Labels: area/fate, breaking/consensus, kind/feature
