Repository aeternity/aeternity, pull requests merged in 2019-09, with the labels that each got.

#2704 Pt 167889960 disallow claiming test registrar
  apps/aechannel/test/aesc_txs_SUITE.erl
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/src/aec_governance.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aens/src/aens_utils.erl
  apps/aens/test/aens_SUITE.erl
  apps/aens/test/aens_test_utils.erl
  apps/aens/test/aens_utils_test.erl
  apps/aeprimop/src/aeprimop.erl
  system_test/common/aest_names_SUITE.erl
  test/name_resolution_SUITE.erl
Labels: area/names

#2713 Pt 168132312 new name hash
  apps/aecore/src/aec_governance.erl
  apps/aens/src/aens.erl
  apps/aens/src/aens_hash.erl
  apps/aens/src/aens_utils.erl
  apps/aens/test/aens_SUITE.erl
  apps/aens/test/aens_test_utils.erl
  docs/release-notes/next-lima/PT-168132312-new-name-hash
Labels: area/names

#2720 Pt lima claim fee
  apps/aechannel/test/aesc_txs_SUITE.erl
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/src/aec_governance.erl
  apps/aecore/src/aec_vm_chain.erl
  apps/aefate/src/aefa_chain_api.erl
  apps/aefate/src/aefa_fate_op.erl
  apps/aehttp/priv/swagger.json
  apps/aehttp/src/aehttp_dispatch_int.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aens/src/aens_claim_tx.erl
  apps/aens/test/aens_SUITE.erl
  apps/aens/test/aens_test_utils.erl
  apps/aeprimop/src/aeprimop.erl
  apps/aetx/src/aetx.erl
  apps/aevm/src/aevm_ae_primops.erl
  apps/aevm/src/aevm_chain_api.erl
  config/swagger.yaml
  rebar.config
  rebar.lock
  test/contracts/aens.aes
  test/contracts/stdlib_tests.aes
  test/name_resolution_SUITE.erl
Labels: area/names

#2727 Pt lima price name under consensus
  apps/aechannel/test/aesc_txs_SUITE.erl
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/src/aec_governance.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aens/test/aens_SUITE.erl
  apps/aens/test/aens_test_utils.erl
  apps/aeprimop/src/aeprimop.erl
  test/contracts/aens.aes
  test/name_resolution_SUITE.erl
Labels: area/names

#2734 Fix SC system tests
  apps/aechannel/src/aesc_session_noise.erl
Labels: area/statechannels

#2731 Pt lima bidding
  apps/aechannel/test/aesc_txs_SUITE.erl
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/src/aec_governance.erl
  apps/aecore/src/aec_trees.erl
  apps/aefate/src/aefa_chain_api.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aens/src/aens_auctions.erl
  apps/aens/src/aens_hash.erl
  apps/aens/src/aens_state_tree.erl
  apps/aens/test/aens_SUITE.erl
  apps/aeprimop/src/aeprimop.erl
  apps/aeprimop/src/aeprimop_state.erl
  apps/aeutils/priv/aeternity_config_schema.json
  test/name_resolution_SUITE.erl
Labels: area/names

#2735 Pt 168256738 fix sum total
  apps/aecore/src/aec_trees.erl
  apps/aecore/test/aec_chain_tests.erl
  apps/aens/src/aens_state_tree.erl
  apps/aeprimop/src/aeprimop.erl
Labels: area/names

#2739 [PT-168283496] Change configuration option name `ws_handlers` to `sc_ws_handlers`
  apps/aehttp/src/sc_ws_handler.erl
  apps/aeutils/priv/aeternity_config_schema.json
  docs/release-notes/next-lima/PT-168283496-change-configuration-ws-handlers.md
Labels: area/statechannels

#2737 Improve client protocol error handling in SC FSMs
  apps/aechannel/src/aesc_chain_watcher.erl
  apps/aechannel/src/aesc_codec.erl
  apps/aechannel/src/aesc_codec.hrl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_offchain_update.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next-lima/PT-168160333-improved-error-handling.md
  docs/state-channels/fsm.puml
Labels: area/statechannels

#2748 Swagger cleanup
  .circleci/config.yml
  .dockerignore
  .gitignore
  Makefile
  apps/aehttp/Makefile
  apps/aehttp/priv/swagger.json
  apps/aehttp/priv/swagger.yaml
  apps/aehttp/src/aehttp_api_validate.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_spec_SUITE.erl
  deployment/deploy_api_docs.sh
  docs/api.md
  py/Makefile
  py/hack_dry_run_input.py
  py/hack_ga_object.py
  py/requirements-win32.txt
  py/requirements.txt
  py/tests/integration/common.py
  py/tests/integration/test_api_usage_contracts_counter.rst
  py/tests/integration/test_contracts.py
  py/tests/integration/test_spend_tx.py
  py/tests/integration/test_unsigned_tx.py
  py/tests/integration/test_use_cases.py
  py/tests/release.py
  py/tests/swagger-version-check.py
  rebar.config
  swagger/check
Labels: kind/cleanup

#2742 [PT-168286967] Support OTP 21
  .circleci/config.yml
  apps/aechannel/src/aesc_chain_watcher.erl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_listeners.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecontract/src/aecontract.app.src
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecontract/test/aect_test_utils.erl
  apps/aecore/src/aec_db.erl
  apps/aecore/src/aec_keys.erl
  apps/aecore/src/aec_metrics_rpt_dest.erl
  apps/aecore/src/aec_split_check.erl
  apps/aecore/src/aec_tx_pool.erl
  apps/aecore/test/aec_accounts_trees_tests.erl
  apps/aecore/test/aec_eunit_SUITE.erl
  apps/aecore/test/aec_metrics_rpt_dest_tests.erl
  apps/aecore/test/aec_test_app_checker.erl
  apps/aecore/test/aec_test_event_handler.erl
  apps/aecore/test/aec_tx_pool_tests.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aega/test/aega_SUITE.erl
  apps/aehttp/src/aehttp_api_handler.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_ga_SUITE.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aens/test/aens_SUITE.erl
  apps/aeprimop/src/aeprimop.erl
  apps/aestratum/test/aestratum_client_suite_utils.erl
  apps/aeutils/include/aeu_stacktrace.hrl
  apps/aevm/src/aevm_ae_primops.erl
  apps/aevm/test/aevm_test_utils.erl
  rebar.config
  system_test/common/aest_sync_SUITE.erl
  system_test/common/helpers/aest_docker.erl
  system_test/common/helpers/aest_external.erl
Labels: area/ci, enhancement, kind/cleanup

#2746 State Channels off-chain pinned env
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next-lima/PT-165214367_offchain_pinned_env.md
  system_test/common/aest_channels_SUITE.erl
Labels: area/statechannels, enhancement

#2751 Fix osx package on CI
  .circleci/config.yml
  deployment/homebrew/erlang.rb
Labels: area/ci

#2747 Fix the (invalid) swagger schema
  apps/aehttp/priv/swagger.yaml
  apps/aehttp/src/aehttp_helpers.erl
  apps/aehttp/test/aehttp_contracts_SUITE.erl
  apps/aehttp/test/aehttp_dryrun_SUITE.erl
  apps/aehttp/test/aehttp_ga_SUITE.erl
  py/tests/integration/common.py
  py/tests/release.py
Labels: area/api, kind/cleanup

#2732 Stick to erlang 21 in OSX build docs
  docs/build.md
Labels: area/docs

#2757 Improve debug logging in SC FSM
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aeutils/include/aeu_stacktrace.hrl
Labels: area/statechannels, kind/cleanup

#2760 PT-168213408 Get protocol version from on-chain environment (key block header)
  apps/aechannel/src/aesc_fsm.erl
Labels: area/statechannels

#2630 [PT-164136571] State channel cache encryption
  .circleci/config.yml
  apps/aechannel/src/aesc_db.erl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_offchain_state.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/src/aesc_state_cache.erl
  apps/aechannel/src/aesc_state_password_wrapper.erl
  apps/aechannel/src/aesc_utils.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/src/aec_db.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next-lima/PT-164136571-encrypt-cached-state-channel-state.md
  system_test/common/aest_db_SUITE.erl
Labels: area/statechannels

#2767 Dont benchmark in CI + less logging in aesc_fsm_SUITE
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/ci, area/statechannels, kind/cleanup

#2692 CircleCI windows builds
  .circleci/config.yml
  .circleci/windows/build.cmd
  .circleci/windows/build.sh
  .circleci/windows/msys2_prepare.cmd
  .circleci/windows/package.cfg
  .circleci/windows/test.cmd
  .circleci/windows/vcvarsall.cmd
  docs/build-windows.md
  scripts/windows/install_erlang.cmd
  scripts/windows/install_msys2.cmd
  scripts/windows/msys2_env_build.sh
  scripts/windows/msys2_prepare.bat
  scripts/windows/msys2_shell.bat
Labels: area/ci

#2768 Improve System Tests stability
  apps/aechannel/src/aesc_fsm.erl
  system_test/common/aest_channels_SUITE.erl
  system_test/common/aest_db_SUITE.erl
  system_test/common/helpers/aest_api.erl
Labels: area/statechannels, area/tests, kind/bug

#2775 Sync lima rc
  VERSION
  apps/aehttp/priv/swagger.yaml
  ci/appveyor/package.cfg
  docs/installation.md
  docs/release-notes/RELEASE-NOTES-5.0.0-rc.2.md
  docs/release-notes/next-lima/PT-000_drop-rename_db_command.md
  docs/release-notes/next-lima/PT-164136571-encrypt-cached-state-channel-state.md
  docs/release-notes/next-lima/PT-165214367_offchain_pinned_env.md
  docs/release-notes/next-lima/PT-167756238-docker_entrypoint.md
  docs/release-notes/next-lima/PT-168132312-new-name-hash
  docs/release-notes/next-lima/PT-168160333-improved-error-handling.md
  docs/release-notes/next-lima/PT-168242015-no_detailed_errors_under_consensus.md
  docs/release-notes/next-lima/PT-168283496-change-configuration-ws-handlers.md
Labels: release

#2776 Remove appveyor
  .circleci/config.yml
  Makefile
  README.md
  appveyor.yml
  ci/appveyor/build.bat
  ci/appveyor/build.ps1
  ci/appveyor/linux_prepare.sh
  ci/appveyor/package.bat
  ci/appveyor/package.cfg
  ci/appveyor/test.bat
  ci/appveyor/util.ps1
Labels: area/ci

#2790 Reconnect regardless of previous WS connection
  apps/aehttp/src/sc_ws_handler.erl
Labels: area/statechannels

#2639 [PT-160544356] Dynamic SC transaction confirmation times
  apps/aechannel/src/aesc_chain_watcher.erl
  apps/aechannel/src/aesc_codec.erl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next-lima/PT-160544356-sc-confirmation-times.md
Labels: area/statechannels, area/tests, kind/feature

#2792 Fix issues in system tests related to not using block hash in SC tests
  apps/aechannel/src/aesc_fsm.erl
  system_test/common/aest_channels_SUITE.erl
  system_test/common/aest_db_SUITE.erl
  system_test/common/aest_mempool_SUITE.erl
  system_test/common/helpers/aest_api.erl
  system_test/common/helpers/aest_nodes.erl
Labels: area/ci, area/statechannels, area/tests, kind/bug

#2803 Disable SC state cache encryption
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next-lima/sc-postpone-state-password.md
Labels: area/statechannels
