Repository aeternity/aeternity, pull requests merged in 2019-10, with the labels that each got.

#2808 Document database backend configuration notes
  docs/configuration.md
Labels: area/docs

#2801 Port of aeuniverse-demo branch to master
  apps/aechannel/src/aechannel.app.src
  apps/aechannel/src/aesc_chain_watcher.erl
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_offchain_state.erl
  apps/aechannel/src/aesc_offchain_tx.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/src/aesc_state_cache.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/src/sc_ws_utils.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  apps/aehttp/test/aehttp_ws_test_utils.erl
Labels: area/statechannels, area/tests

#2827 SC: Fix log ordering for channel create tests
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, area/tests, kind/bug

#2824 SC: Add testing debug switch via `CT_DEBUG`
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, area/tests

#2825 SC: Update documentation for dynamic min_depth calculation
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
Labels: area/docs, area/statechannels

#2815 Adding (uat_)contract.json + tests and Readme
  apps/aecontract/test/mtree.erl
  apps/aecore/test/aec_block_fork_tests.erl
  data/aecore/.lima/Readme.md
  data/aecore/.lima/contracts.json
  data/aecore/.lima/contracts_uat.json
  test/json/contracts_accounts.json
  test/json/uat_contracts_accounts.json
Labels: release

#2810 Add some ping pong tests at open times
  apps/aehttp/test/aehttp_sc_SUITE.erl
Labels: area/statechannels, area/tests, kind/feature

#2831 Mechanism for handling an `extra_accounts.json` file in Lima HF
  apps/aecore/src/aec_block_fork.erl
  apps/aecore/src/aec_fork_block_settings.erl
  apps/aecore/test/aec_block_fork_tests.erl
  apps/aecore/test/aec_eunit_SUITE.erl
  apps/aecore/test/aec_test_utils.erl
  data/aecore/.lima/extra_accounts.json
  data/aecore/.lima/extra_accounts_test.json
  data/aecore/.lima/extra_accounts_uat.json
  docs/release-notes/next-lima/extra_accounts_json.md
  rebar.config
Labels: release

#2830 Set testnet and mainnet heights for Lima hardfork (aiming 16th and 30th of Oct)
  apps/aecore/src/aec_hard_forks.erl
  docs/release-notes/next-lima/PT-168425449-lima-heights.md
Labels: release

#2844 SC: Improve timing in throughput tests
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, area/tests, kind/cleanup

#2848 Add build switch to skip compilation of rocksdb
  rebar.config.script
  rebar.lock.script
Labels: kind/cleanup

#2833 Unify the WS and FSM client messages
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_offchain_state.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, kind/cleanup

#2879 Refactor fsm message log and reporting
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_window.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, kind/cleanup

#2902 SC: Add missing channel_id in channel_reestablished report
  apps/aechannel/src/aesc_fsm.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
Labels: area/statechannels, kind/bug

#2905 ST channels test: fix race
  system_test/common/aest_channels_SUITE.erl
  system_test/common/aest_channels_SUITE_data/aeternity.yaml.mustache
Labels: area/statechannels, area/tests, kind/bug

#2868 Miner signalled consensus
  apps/aecore/include/aec_db.hrl
  apps/aecore/src/aec_block_genesis.erl
  apps/aecore/src/aec_block_key_candidate.erl
  apps/aecore/src/aec_blocks.erl
  apps/aecore/src/aec_chain_state.erl
  apps/aecore/src/aec_db.erl
  apps/aecore/src/aec_hard_forks.erl
  apps/aecore/src/aec_headers.erl
  apps/aecore/src/aecore.app.src
  apps/aecore/test/aec_block_key_candidate_tests.erl
  apps/aecore/test/aec_chain_state_tests.erl
  apps/aecore/test/aec_conductor_tests.erl
  apps/aecore/test/aec_headers_tests.erl
  apps/aecore/test/aec_test_utils.erl
  apps/aens/src/aens_claim_tx.erl
  apps/aetx/src/aetx_env.erl
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/test/aeu_env_tests.erl
  apps/aeutils/test/data/epoch_invalid_fork_signalling_block_count.yaml
  apps/aeutils/test/data/epoch_invalid_fork_signalling_interval.yaml
  apps/aeutils/test/data/epoch_invalid_fork_signalling_network_config.yaml
  apps/aeutils/test/data/epoch_invalid_fork_signalling_start_height.yaml
  apps/aeutils/test/data/epoch_invalid_fork_signalling_version.yaml
  apps/aeutils/test/data/epoch_invalid_fork_signalling_version2.yaml
  docs/release-notes/next-lima/miner-signalled-consensus.md
  system_test/common/aest_community_fork_SUITE.erl
  system_test/common/aest_community_fork_SUITE_data/aeternity.yaml.mustache
  system_test/common/helpers/aest_docker.erl
Labels: area/core, kind/feature

#2910 Fix community fork system test
  system_test/common/aest_community_fork_SUITE.erl
  system_test/common/aest_community_fork_SUITE_data/aeternity.yaml.mustache
Labels: area/core, kind/bug

#2913 Fix missing aec_signal_count table
  apps/aecore/src/aec_db.erl
Labels: area/core, kind/bug

#2908 Upgrade rebar3 to 3.12.0
  rebar3
Labels: area/build-system, kind/improvement

#2925 Remove type check for CONS
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aefate/src/aefa_fate.erl
  apps/aefate/src/aefa_fate_op.erl
  apps/aefate/test/aefate_engine_test.erl
  docs/release-notes/next/list_of_maps.md
  test/contracts/list_of_maps.aes
Labels: release

#2927 Improve sc noise stability
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, kind/improvement

#2885 SC FSM: add optional fees to on-chain transactions
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next/SC_FSM_optional_fees.md
Labels: area/statechannels, kind/feature

#2931 Prepare 5.0.0
  .circleci/config.yml
  VERSION
  apps/aehttp/priv/swagger.yaml
  ci/appveyor/package.cfg
  docs/installation.md
  docs/release-notes/RELEASE-NOTES-5.0.0.md
  docs/release-notes/next/catch_inner_process_crashes_in_ga_meta.md
  docs/release-notes/next/fix_aens_commitment_hash_error.md
  docs/release-notes/next/list_of_maps.md
  rebar.config
Labels: area/docs, release

#2934 Align OTP versions with docker image configuration
  .circleci/config.yml
Labels: area/ci, kind/bug

#2936 Back-merge 5.0.0
  VERSION
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aefate/src/aefa_engine_state.erl
  apps/aefate/src/aefa_fate.erl
  apps/aefate/src/aefa_fate_op.erl
  apps/aefate/test/aefate_engine_test.erl
  apps/aega/src/aega_meta_tx.erl
  apps/aehttp/priv/swagger.yaml
  apps/aens/src/aens.erl
  apps/aeprimop/src/aeprimop.erl
  docs/installation.md
  docs/release-notes/RELEASE-NOTES-5.0.0-rc.6.md
  docs/release-notes/RELEASE-NOTES-5.0.0.md
  rebar.config
  test/contracts/call_caller.aes
  test/contracts/list_of_maps.aes
  test/contracts/sophia_2/call_caller.aes
Labels: release

#2933 GH 2932 Fix test issues
  apps/aecore/test/aecore_suite_utils.erl
Labels: area/statechannels, area/tests, kind/bug

#2938 Rename aetx:min_gas into aetx:fee_gas
  apps/aechannel/src/aesc_fsm.erl
  apps/aestratum/src/aestratum.erl
  apps/aetx/src/aetx.erl
Labels: area/core, kind/improvement

#2805 SC: WS Handler hogs the jobs pool
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_limits.erl
  apps/aechannel/src/aesc_sup.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/src/aeu_env.erl
  docs/release-notes/next-lima/PT-168782034-sc_load-regulation.md
Labels: area/statechannels, kind/bug

#2941 Update erlang-lz4 to latest upstream
  .circleci/config.yml
  rebar.config
  rebar.lock
Labels: dependencies

#2946 Reset CI machine build cache
  .circleci/config.yml
Labels: area/ci, kind/bug

#2947 Increment missed cache keys
  .circleci/config.yml
Labels: area/ci, kind/bug

#2806 SC: Add ability to cancel update initiated by self
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next/PT-168289008_SC_soft_reject.md
Labels: area/statechannels, kind/feature

#2958 Use safe mining setup during integration tests
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/test/aehttp_integration_SUITE.erl
Labels: area/tests, kind/bug

#2960 Prevent race condition by creating monitors earlier
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/tests, kind/bug
