Repository aeternity/aeternity, pull requests merged in 2020-04, with the labels that each got.

#3199 Include channel IDs at fork point height
  apps/aechannel/src/aesc_chain_watcher.erl
  apps/aechannel/test/aesc_chain_watcher_SUITE.erl
Labels: area/statechannels, kind/bug

#3191 Gh3190 responder accept crash
  apps/aechannel/src/aesc_listeners.erl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  docs/release-notes/next-iris/GH-3190-state-channel-acceptor-crash.md
Labels: area/statechannels, kind/bug

#3202 Fix ST
  apps/aecore/src/aec_conductor.erl
  apps/aecore/src/aecore_app.erl
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/test/data/epoch_full.yaml
  system_test/common/aest_channels_SUITE.erl
  system_test/common/aest_channels_SUITE_data/aeternity.yaml.mustache
  system_test/common/helpers/aest_docker.erl
Labels: area/tests, kind/bugfix

#3212 Improve release notes for 5.5.1
  docs/release-notes/next/GH-3128_FSM_detects_FP.md
  docs/release-notes/next/GH-3190-state-channel-acceptor-crash.md
Labels: area/docs, kind/improvement

#3211 Fix (with height protection) current contract issue
  apps/aecore/include/blocks.hrl
  apps/aecore/test/aec_mining_tests.erl
  apps/aefate/src/aefa_engine_state.erl
  docs/release-notes/next/GH-3184-fix-contract-check.md
Labels: area/core, area/fate, kind/bugfix

#3210 chain watcher stays silent if it has no registered requests
  apps/aechannel/src/aesc_chain_watcher.erl
Labels: area/statechannels, kind/bug

#3214 Bump version to 5.5.1 and add combined release notes
  VERSION
  apps/aehttp/priv/swagger.yaml
  docs/release-notes/RELEASE-NOTES-5.5.1.md
  docs/release-notes/next/.keep
  docs/release-notes/next/GH-3128_FSM_detects_FP.md
  docs/release-notes/next/GH-3184-fix-contract-check.md
  docs/release-notes/next/GH-3190-state-channel-acceptor-crash.md
Labels: area/release

#3201 Refactor miner_loop interaction for better debugging
  apps/aechannel/test/aesc_fsm_SUITE.erl
Labels: area/statechannels, area/tests

#3220 Update github issue template
  ISSUE_TEMPLATE.md
Labels: area/docs, kind/improvement

#3219 Clarify configuration for protocol_beneficiaries
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/test/data/epoch_full.yaml
Labels: area/docs, kind/improvement

#3222 future proof rebar.lock.script
  rebar.lock.script
Labels: area/build-system, kind/improvement

#3221 Fix intendation in stratum docs
  docs/stratum.md
Labels: area/docs, kind/bugfix

#3207 Fix aec_chain:get_transactions_between/2
  apps/aecore/src/aec_chain.erl
  apps/aecore/test/aec_chain_tests.erl
Labels: area/statechannels, area/tests, kind/improvement

#3227 Bump info to 5.5.2
  .circleci/config.yml
  VERSION
  apps/aecore/include/blocks.hrl
  apps/aecore/test/aec_mining_tests.erl
  apps/aefate/src/aefa_engine_state.erl
  apps/aehttp/priv/swagger.yaml
  docs/release-notes/RELEASE-NOTES-5.5.2.md
Labels: area/release

#3224 Gh3169 sc reestablish early 2
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_fsm.hrl
  apps/aechannel/src/aesc_session_noise.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/state-channels/fsm.puml
Labels: area/statechannels

#3206 Update aesophia_cli to 4.3.1
  apps/aecontract/test/aect_test_utils.erl
  rebar.config
Labels: area/core

#3223 Re-ordering github helper files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  WE-ARE-HIRING.md
Labels: area/docs

#3240 Re-ordered variables
  apps/aecore/src/aec_tx_pool.erl
Labels: area/core, kind/improvement
