Repository aeternity/aeternity, pull requests merged in 2020-05, with the labels that each got.

#3257 Add release notes for GH-3256
  docs/release-notes/next/GH-3256-bugfix-contract-store.md
Labels: area/docs, area/release

#3256 Unfold store maps in return value from remote call using the correct …
  apps/aefate/src/aefa_fate.erl
Labels: area/core, kind/bugfix

#3260 Prepare 5.5.4 release
  VERSION
  apps/aecore/include/blocks.hrl
  apps/aecore/test/aec_mining_tests.erl
  apps/aehttp/priv/swagger.yaml
  docs/release-notes/RELEASE-NOTES-5.5.4.md
  docs/release-notes/next/GH-3229_missing_FP_info.md
  docs/release-notes/next/GH-3256-bugfix-contract-store.md
  docs/release-notes/next/fix_close_mutual_fee_issue.md
Labels: area/release

#3258 Fix github templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: area/docs

#3263 Allow empty issue reports
  .github/ISSUE_TEMPLATE/config.yml
Labels: kind/bugfix

#3165 Gh3154 fetch log via sc ws
  Makefile
  apps/aechannel/src/aesc_fsm.erl
  apps/aechannel/src/aesc_window.erl
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aehttp/src/sc_ws_api.erl
  apps/aehttp/src/sc_ws_api_jsonrpc.erl
  apps/aehttp/src/sc_ws_handler.erl
  apps/aehttp/test/aehttp_sc_SUITE.erl
  docs/release-notes/next/CG-3154-fetch-log-via-sc-ws.md
Labels: area/statechannels, kind/feature

#3270 Wrong ulimit suggestion
  hooks/pre_start.sh
Labels: area/docs, kind/improvement

#3271 Added CORS headers for error responses
  apps/aehttp/src/aehttp_app.erl
  docs/release-notes/next/GH-3192-cors-headers.md
Labels: area/api, kind/bugfix
