Repository aeternity/aeternity, pull requests merged in 2024-01, with the labels that each got.

#4200 Add ability to configure directories for hard forks
  apps/aecore/src/aec_block_fork.erl
  apps/aecore/src/aec_consensus_hc.erl
  apps/aecore/src/aec_consensus_smart_contract.erl
  apps/aecore/src/aec_fork_block_settings.erl
  apps/aecore/src/aec_hard_forks.erl
  apps/aecore/src/aec_trees.erl
  apps/aecore/test/aec_fork_block_settings_tests.erl
  apps/aecore/test/aec_test_utils.erl
  apps/aecore/test/aecore_suite_utils.erl
  apps/aehttp/test/aehttp_stake_contract_SUITE.erl
  apps/aeutils/priv/aeternity_config_schema.json
  apps/aeutils/src/aeu_env.erl
  apps/aeutils/test/data/epoch_full.yaml
  docs/configuration.md
  system_test/common/aest_sync_SUITE.erl
  system_test/common/aest_sync_SUITE_data/v1.4.0/aeternity.yaml.mustache
  system_test/common/helpers/aest_docker.erl
Labels: kind/feature

#4237 [Ceres] Restrict GAAttachTx - only allowed for fresh accounts
  apps/aega/src/aega_attach_tx.erl
  apps/aega/test/aega_SUITE.erl
  docs/release-notes/next-ceres/aega_only_allow_attach_for_fresh_accounts.md
Labels: breaking/consensus

#4251 [HC]: configuration cleanup/overhaul
  apps/aecore/src/aec_consensus_hc.erl
  apps/aecore/src/aec_parent_connector.erl
  apps/aehttp/src/aehttpc.erl
  apps/aehttp/src/aehttpc_aeternity.erl
  apps/aehttp/src/aehttpc_btc.erl
  apps/aehttp/src/aehttpc_doge.erl
  apps/aehttp/test/aehttp_parent_connector_tests.erl
  apps/aehttp/test/aehttp_stake_contract_SUITE.erl
  apps/aeutils/priv/aeternity_config_schema.json
Labels: area/hyperchains

#4255 FATE: AENSv2.DataPt should contain FATE_BYTES
  apps/aefate/src/aefa_fate_op.erl
  test/contracts/aens_lookup.aes
Labels: breaking/consensus, area/fate, kind/bugfix
