Repository aeternity/aeternity, pull requests merged in 2024-02, with the labels that each got.

#4264 Improve aesc_fsm_SUITE - close FSM clients after tests
  apps/aechannel/test/aesc_fsm_SUITE.erl
  apps/aechannel/test/aesc_htlc_SUITE.erl
Labels: area/statechannels, area/tests

#4263 HC/FATE: fix issue when calling Chain.blockhash on a competing key-block
  apps/aecontract/test/aecontract_SUITE.erl
  apps/aecore/src/aec_consensus_hc.erl
  apps/aefate/src/aefa_chain_api.erl
  apps/aefate/src/aefa_fate_op.erl
  apps/aehttp/test/aehttp_stake_contract_SUITE.erl
Labels: kind/bug, breaking/consensus

#4270 Make the BRI optional per protocol version
  apps/aecore/src/aec_dev_reward.erl
  apps/aeutils/priv/aeternity_config_schema.json
Labels: kind/feature

#4271 Add missing meck-call in eunit test (not manifesting)
  apps/aecore/test/aec_parent_chain_cache_tests.erl
Labels: release/ignore

#4272 Fix incorrect hashrate computation for status endpoint
  apps/aehttp/src/aehttp_dispatch_ext.erl
Labels: area/api
